version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    working_directory: ~/node
    steps:
      - checkout:
      - run:
          name: install npm dependencies
          command: |
            npm install --save
      - run:
          name: transpile code
          command: |
            npx tsc
      - run:
          name: run tests
          command: |
            npm run test
workflows:
  build_tests:
    jobs:
      - run_tests
