version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    working_directory: ~/node
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: |
            yarn install
      - run:
          name: transpile code
          command: |
            sudo npm install typescript -g
            npx tsc
workflows:
  build_tests:
    jobs:
      - run_tests
